# Generated by Django 4.0.4 on 2022-05-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=20),
            preserve_default=False,
        ),
    ]
